name       : drkonqi
version    : 5.21.4
release    : 62
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.4/drkonqi-5.21.4.tar.xz : 5831bad85f1f253844747e5c257996ab0a277ce20887abd58e72eaef3d047488
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - kcrash-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - syntax-highlighting-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
