name       : drkonqi
version    : 5.14.3
release    : 24
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.3/drkonqi-5.14.3.tar.xz : 319dd773132b059ebeacfa6a75e983a983f2afe926797bc7ea38cb5c88ab6886
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kxmlrpcclient-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
