name       : drkonqi
version    : 5.18.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.3/drkonqi-5.18.3.tar.xz : ca319ed5d7c74a282506ee3f07ed94c823a679c7c731e8a6eed065d00f404fd4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcrash-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlrpcclient-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
