name       : drkonqi
version    : 5.27.6
release    : 85
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.6/drkonqi-5.27.6.tar.xz : f95e169790af38621635c35af21c6785c9b64f64608a4ce09226762e7ba8ca13
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - kcrash-devel
    - kdeclarative-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kuserfeedback-devel
    - kwallet-devel
    - syntax-highlighting-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
