name       : drkonqi
version    : 5.20.3
release    : 55
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.3/drkonqi-5.20.3.tar.xz : 9a0e9c3632ab4c6e7b0dc01b549b24b051cb65c9d11be00166661c6dd5bbdaf0
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcrash-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlrpcclient-devel
    - syntax-highlighting-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
