name       : drkonqi
version    : 5.21.2
release    : 60
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.2/drkonqi-5.21.2.tar.xz : c1d9dc90d01554ac277f8e1734df45c551f46913c19e44df56267560e047b909
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - kcrash-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - syntax-highlighting-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
