name       : drkonqi
version    : 5.23.1
release    : 69
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.1/drkonqi-5.23.1.tar.xz : 73079b1a3316705f5112bfe232f839d603834ffa4813d776239c26e198d6d3a5
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - kcrash-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - syntax-highlighting-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
