name       : drkonqi
version    : 5.22.2
release    : 65
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/drkonqi-5.22.2.1.tar.xz : 6d3081ae97d536d014394648e97b782f57f06ecef25ef6fbeb6370504d15d30d
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - kcrash-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - syntax-highlighting-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
