name       : drkonqi
version    : 5.20.5
release    : 57
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.5/drkonqi-5.20.5.tar.xz : 09ee110748c3b257aa2f243f683d9d5712d89fb977459ffdb46bc65ab10882e6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcrash-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlrpcclient-devel
    - syntax-highlighting-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
