name       : drkonqi
version    : 5.27.7
release    : 86
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/drkonqi-5.27.7.tar.xz : e82716415c22a3d6cf90e2380a64cbf5d7d171ab32d02cd29056bced0b9221d2
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - kcrash-devel
    - kdeclarative-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kuserfeedback-devel
    - kwallet-devel
    - syntax-highlighting-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
