name       : drkonqi
version    : 5.18.5
release    : 46
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.5/drkonqi-5.18.5.tar.xz : b1a626c4ed2f9de8f8bc3359d8827e7fa6ac17486b8477674e47627fcf6efad1
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcrash-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlrpcclient-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
