name       : drkonqi
version    : 5.15.4
release    : 29
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.4/drkonqi-5.15.4.tar.xz : 8e3b46525f792d5c3264f0d835e7180cda4a0dbd78cd8055f13e166151a6c3de
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kcrash-devel
    - ki18n-devel
    - kidletime-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kxmlrpcclient-devel
rundep     :
    - gdb
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
